---
- name: Make sure chrony is not present
  package:
    name: "chrony"
    state: absent

- name: Install ntp package
  package:
    name: "{{ item }}"
    state: present
#  with_items: "{{ role_ntpserver_packages }}"
  loop: "{{ role_ntpserver_packages|flatten(levels=1) }}"

- name: TEMPORARY - copy config file
  copy:
    src: ../files/ntp.conf
    dest: /etc/ntp.conf
  register: role_ntpserver_config
# TODO
#- name: Prepare configuration statements

- name: Enable ntpd
  service:
    name: "ntpd"
    enabled: yes

- name: Restart ntpd if configuration has changed
  service:
    name: "ntpd"
    state: restarted
  when: role_ntpserver_config.changed


#- name: Sync local time
#
